#pragma once

#define REL32_DISPLACEMENT_SIZE 0x4
#define ADDR64_ADDRESS_SIZE 0x8

#define OFF_ADDRBLACKLISTSTR_PTR 0x15C
#define OFF_BLACKLISTARRAY_DATA 0x17C
#define OFF_COMPAREWIDESTRINGS 0x0
#define OFF_DATA_SIZE 0x28
#define OFF_ORIGINALLDRLOADDLLBYTES_PTR 0x16C
#define OFF_REALLOADLIBRARY_PTR 0x164
#define OFF_REHOOKBYTES_PTR 0x174
#define OFF_REMOTESTUB 0x2A
#define OFF_TEXT_MN_SIZE 0x15C
